# Generated by Django 3.2.3 on 2021-06-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='part')),
                ('part_number', models.IntegerField(blank=True, null=True, verbose_name='part_number')),
            ],
        ),
        migrations.RemoveField(
            model_name='mainstory',
            name='part',
        ),
        migrations.RemoveField(
            model_name='mainstory',
            name='part_number',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/image/product_image/%Y/%m/%d', verbose_name='IMAGE'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_story.mainstory'),
        ),
        migrations.AlterField(
            model_name='image',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='small_image/%Y/%m/%d', verbose_name='small_image'),
        ),
        migrations.AlterField(
            model_name='mainstory',
            name='context1',
            field=models.TextField(blank=True, db_index=True, max_length=10000, null=True, verbose_name='context1'),
        ),
        migrations.AlterField(
            model_name='mainstory',
            name='context2',
            field=models.TextField(blank=True, db_index=True, max_length=10000, null=True, verbose_name='context2'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='static/image/product_video/%Y/%m/%d', verbose_name='video'),
        ),
    ]
