# Generated by Django 3.2.3 on 2021-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_story', '0002_auto_20210618_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstory',
            name='part',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='part'),
        ),
        migrations.AddField(
            model_name='mainstory',
            name='part_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='part_number'),
        ),
    ]
