# Generated by Django 3.2.3 on 2021-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_story', '0004_auto_20210625_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstory',
            name='context1',
            field=models.TextField(blank=True, db_index=True, max_length=2600, null=True, verbose_name='context1'),
        ),
        migrations.AlterField(
            model_name='mainstory',
            name='context2',
            field=models.TextField(blank=True, db_index=True, max_length=2600, null=True, verbose_name='context2'),
        ),
    ]
