# Generated by Django 3.2.3 on 2021-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=30, verbose_name='ip')),
                ('accesscount', models.IntegerField(max_length=10000, verbose_name='Access Count')),
                ('access_dt', models.DateTimeField(auto_now_add=True, verbose_name='Access Date')),
            ],
            options={
                'ordering': ('-access_dt',),
            },
        ),
    ]
