# Generated by Django 3.2.3 on 2021-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesshistory',
            name='browser_name',
            field=models.CharField(db_index=True, default='chrome', max_length=50, verbose_name='browser_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='browser_version',
            field=models.CharField(db_index=True, default='tokyo', max_length=30, verbose_name='browser_version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='device_name',
            field=models.CharField(db_index=True, default='mama', max_length=30, verbose_name='device_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='device_os',
            field=models.CharField(db_index=True, default='10.10', max_length=30, verbose_name='device_os'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='path',
            field=models.CharField(db_index=True, default='tokyo', max_length=100, verbose_name='path'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='title',
            field=models.CharField(db_index=True, default='tokyo', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesshistory',
            name='accesscount',
            field=models.IntegerField(blank=True, verbose_name='Access Count'),
        ),
        migrations.AlterField(
            model_name='accesshistory',
            name='ip',
            field=models.CharField(db_index=True, max_length=30, verbose_name='ip_address'),
        ),
    ]
