# Generated by Django 3.2.3 on 2021-07-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moveHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, default='default', max_length=30, verbose_name='ip_address')),
                ('path', models.CharField(db_index=True, default='default', max_length=100, verbose_name='path')),
                ('cursor_id', models.CharField(db_index=True, default='default', max_length=100, verbose_name='cursor_id')),
                ('layerX', models.IntegerField(verbose_name='layerX')),
                ('layerY', models.IntegerField(verbose_name='layerY')),
                ('offsetX', models.IntegerField(default=0, verbose_name='offsetX')),
                ('offsetY', models.IntegerField(default=0, verbose_name='offsetY')),
                ('width', models.IntegerField(db_index=True, default=0, verbose_name='Width')),
                ('height', models.IntegerField(db_index=True, default=0, verbose_name='Height')),
                ('clientX', models.DecimalField(db_index=True, decimal_places=15, max_digits=30, verbose_name='clientX')),
                ('clientY', models.DecimalField(db_index=True, decimal_places=15, max_digits=30, verbose_name='clientY')),
                ('record_dt', models.DateTimeField(auto_now_add=True, verbose_name='record DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
        ),
        migrations.CreateModel(
            name='pointCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, default='default', max_length=30, verbose_name='ip_address')),
                ('pointX', models.DecimalField(db_index=True, decimal_places=15, max_digits=30, verbose_name='PointX')),
                ('pointY', models.DecimalField(db_index=True, decimal_places=15, max_digits=30, verbose_name='PointY')),
                ('width', models.IntegerField(db_index=True, default=0, verbose_name='Width')),
                ('height', models.IntegerField(db_index=True, default=0, verbose_name='Height')),
                ('device_name', models.CharField(db_index=True, default='default', max_length=30, verbose_name='device_name')),
                ('path', models.CharField(db_index=True, default='default', max_length=100, verbose_name='path')),
                ('cursor_id', models.CharField(db_index=True, default='default', max_length=100, verbose_name='cursor_id')),
                ('title', models.CharField(db_index=True, default='default', max_length=100, verbose_name='title')),
                ('device_os', models.CharField(db_index=True, default='default', max_length=30, verbose_name='device_os')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='UPLOAD DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
        ),
    ]
